/** Browser-native port of ST The World Clouds3dFX. */
export function createClouds3dFX(target) {
  let viewport = null, world = null, bases = [], layers = [], raf = 0, elapsed = 0, last = 0, density = { count: 1, wind: 1 }
  const css = document.createElement('style')
  const cloudUrl = new URL('../../assets/images/cloud.png', import.meta.url).href
  css.textContent = `#clouds-viewport{position:absolute;inset:0;overflow:hidden;perspective:1000px;z-index:0;pointer-events:none;transform:translateZ(0);backface-visibility:hidden}#clouds-world{position:absolute;left:50%;top:50%;width:512px;height:512px;margin:-256px;transform-style:preserve-3d}#clouds-world div{transform-style:preserve-3d}.cloudBase{position:absolute;left:256px;top:256px;width:20px;height:20px;margin:-10px;transform-style:preserve-3d}.cloudLayer{position:absolute;left:50%;top:50%;width:256px;height:256px;margin:-128px;background:url('${cloudUrl}') center/contain no-repeat;backface-visibility:hidden;transform-style:flat;will-change:transform,filter;transition:filter 7s ease-in-out}`
  document.head.append(css)
  function frame(now) { if (!viewport) return; const dt = last ? Math.min((now-last)/1000,.05) : .016; last=now; elapsed+=dt; const wind=Math.max(0,Number(density.wind)||0), speed=5*(.55+wind*.45), freq=.05+wind*.015, amp=.7+wind*.15; for(const b of bases){let x=+b.dataset.x+elapsed*(+b.dataset.d)*speed; while(x>980)x-=1960; const y=+b.dataset.y+Math.sin(elapsed*freq+(+b.dataset.p))*+b.dataset.a*amp; b.style.transform=`translateX(${x}px) translateY(${y}px) translateZ(${b.dataset.z}px)`} raf=requestAnimationFrame(frame) }
  function generate(next=density){ density=next; world.replaceChildren(); bases=[]; layers=[]; const count=Math.min(36,Math.max(6,Math.floor((density.count>=3?8:10)*density.count))); for(let i=0;i<count;i++){const b=document.createElement('div'); b.className='cloudBase'; Object.assign(b.dataset,{x:900-Math.random()*1800,y:420-Math.random()*840,z:320-Math.random()*640,d:.8+Math.random()*1.6,p:Math.random()*Math.PI*2,a:1+Math.random()*2.5}); world.append(b); bases.push(b); const n=density.count>=3?2+Math.round(Math.random()):3+Math.round(Math.random()*2); for(let j=0;j<n;j++){const c=document.createElement('div'),x=(256-Math.random()*512)*.2,y=(256-Math.random()*512)*.2,z=100-Math.random()*200,a=Math.random()*360,s=.5+Math.random(); c.className='cloudLayer'; c.style.opacity=String(.6+Math.random()*.4); Object.assign(c.dataset,{x,y,z,a,s}); c.style.transform=`translateX(${x}px) translateY(${y}px) translateZ(${z}px) rotateZ(${a}deg) scale(${s})`; b.append(c); layers.push(c)}}}
  return { activate(options={}) { const next = options.density || density; if(viewport){ if(next.count !== density.count || next.wind !== density.wind) generate(next); return } viewport=document.createElement('div'); viewport.id='clouds-viewport'; world=document.createElement('div'); world.id='clouds-world'; viewport.append(world); target.append(viewport); generate(next); raf=requestAnimationFrame(frame) }, setColor(filter){layers.forEach(x=>x.style.filter=filter)}, deactivate(){cancelAnimationFrame(raf);viewport?.remove();viewport=null;world=null;bases=[];layers=[];elapsed=last=0}, dispose(){cancelAnimationFrame(raf);viewport?.remove();css.remove()} }
}
