export const applicationDocumentTypes = {
  cardSource: 'airp.cardSource',
  providerProfile: 'airp.providerProfile',
  aiCapabilityProfile: 'airp.aiCapabilityProfile',
  agentProfile: 'airp.agentProfile',
  agentTool: 'airp.agentTool',
  stateDefinition: 'airp.stateDefinition',
  textTransformRule: 'airp.textTransformRule',
  textExtractor: 'airp.textExtractor',
  textPipelineOverride: 'airp.textPipelineOverride',
  loomScript: 'airp.loomScript',
  loomScriptMount: 'airp.loomScriptMount',
  portableExtensionPayload: 'airp.portableExtensionPayload',
  extensionConfig: 'airp.extensionConfig',
  extensionRecord: 'airp.extensionRecord',
  importBundle: 'airp.importBundle',
  timelineRuntimeContext: 'airp.timelineRuntimeContext',
  timelineArchivePending: 'airp.timelineArchivePending',
} as const
